/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KameraRouteImport } from './routes/kamera'
import { Route as _authenticatedRouteImport } from './routes/__authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as _authenticatedProfilRouteImport } from './routes/__authenticated/profil'
import { Route as _authenticatedPenggunaanBahanKimiaRouteImport } from './routes/__authenticated/penggunaan-bahan-kimia'
import { Route as _authenticatedPencatatanHarianRouteImport } from './routes/__authenticated/pencatatan-harian'
import { Route as _authenticatedLogAktivitasRouteImport } from './routes/__authenticated/log-aktivitas'
import { Route as _authenticatedListDataRouteImport } from './routes/__authenticated/list-data'
import { Route as _authenticatedJadwalRouteImport } from './routes/__authenticated/jadwal'
import { Route as _authenticatedGantiPasswordRouteImport } from './routes/__authenticated/ganti-password'
import { Route as _authenticatedDashboardRouteImport } from './routes/__authenticated/dashboard'
import { Route as _authenticatedComingSoonRouteImport } from './routes/__authenticated/coming-soon'
import { Route as _authenticatedBahanKimiaRouteImport } from './routes/__authenticated/bahan-kimia'
import { Route as _authenticatedAnomaliRouteImport } from './routes/__authenticated/anomali'
import { Route as _authenticatedFormAnomaliRouteImport } from './routes/__authenticated/form/anomali'
import { Route as _authenticatedPagesDetailKodeRouteImport } from './routes/__authenticated/pages/detail/$kode'
import { Route as _authenticatedPagesDetailWtpDebtKodeRouteImport } from './routes/__authenticated/pages/detail-wtp-debt/$kode'
import { Route as _authenticatedPagesDetailSgaiKodeRouteImport } from './routes/__authenticated/pages/detail-sgai/$kode'
import { Route as _authenticatedPagesDetailRsvKodeRouteImport } from './routes/__authenticated/pages/detail-rsv/$kode'
import { Route as _authenticatedPagesDetailPompAtmKodeRouteImport } from './routes/__authenticated/pages/detail-pomp-atm/$kode'
import { Route as _authenticatedPagesDetailPompAmpKodeRouteImport } from './routes/__authenticated/pages/detail-pomp-amp/$kode'
import { Route as _authenticatedPagesDetailPlnKodeRouteImport } from './routes/__authenticated/pages/detail-pln/$kode'
import { Route as _authenticatedPagesDetailPakaiKntrKodeRouteImport } from './routes/__authenticated/pages/detail-pakai-kntr/$kode'
import { Route as _authenticatedPagesDetailMtrHrsKodeRouteImport } from './routes/__authenticated/pages/detail-mtr-hrs/$kode'
import { Route as _authenticatedPagesDetailKwlUaKodeRouteImport } from './routes/__authenticated/pages/detail-kwl-ua/$kode'
import { Route as _authenticatedPagesDetailKimiaKodeRouteImport } from './routes/__authenticated/pages/detail-kimia/$kode'
import { Route as _authenticatedPagesDetailGnstKodeRouteImport } from './routes/__authenticated/pages/detail-gnst/$kode'
import { Route as _authenticatedPagesDetailDosisKodeRouteImport } from './routes/__authenticated/pages/detail-dosis/$kode'
import { Route as _authenticatedPagesDetailCuciKodeRouteImport } from './routes/__authenticated/pages/detail-cuci/$kode'
import { Route as _authenticatedPagesDetailCpltKodeRouteImport } from './routes/__authenticated/pages/detail-cplt/$kode'
import { Route as _authenticatedFormWtpDebtIdRouteImport } from './routes/__authenticated/form/wtp-debt/$id'
import { Route as _authenticatedFormSgaiIdRouteImport } from './routes/__authenticated/form/sgai/$id'
import { Route as _authenticatedFormRsvIdRouteImport } from './routes/__authenticated/form/rsv/$id'
import { Route as _authenticatedFormPompAtmIdRouteImport } from './routes/__authenticated/form/pomp-atm/$id'
import { Route as _authenticatedFormPompAmpIdRouteImport } from './routes/__authenticated/form/pomp-amp/$id'
import { Route as _authenticatedFormPenggunaanBahanKimiaKodeRouteImport } from './routes/__authenticated/form/penggunaan-bahan-kimia/$kode'
import { Route as _authenticatedFormPemakaianKantorIdRouteImport } from './routes/__authenticated/form/pemakaian-kantor/$id'
import { Route as _authenticatedFormPakaiKantorKodeRouteImport } from './routes/__authenticated/form/pakai-kantor/$kode'
import { Route as _authenticatedFormMeterIdRouteImport } from './routes/__authenticated/form/meter/$id'
import { Route as _authenticatedFormMeterPlnIdRouteImport } from './routes/__authenticated/form/meter-pln/$id'
import { Route as _authenticatedFormKwluaIdRouteImport } from './routes/__authenticated/form/kwlua/$id'
import { Route as _authenticatedFormKimiaIdRouteImport } from './routes/__authenticated/form/kimia/$id'
import { Route as _authenticatedFormHoursPompaKodeRouteImport } from './routes/__authenticated/form/hours-pompa/$kode'
import { Route as _authenticatedFormGensetKodeRouteImport } from './routes/__authenticated/form/genset/$kode'
import { Route as _authenticatedFormDosisIdRouteImport } from './routes/__authenticated/form/dosis/$id'
import { Route as _authenticatedFormCuciIdRouteImport } from './routes/__authenticated/form/cuci/$id'
import { Route as _authenticatedFormCipoletyIdRouteImport } from './routes/__authenticated/form/cipolety/$id'
import { Route as _authenticatedFormCuciInputJenisRouteImport } from './routes/__authenticated/form/cuci/input/$jenis'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KameraRoute = KameraRouteImport.update({
  id: '/kamera',
  path: '/kamera',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedRoute = _authenticatedRouteImport.update({
  id: '/__authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedProfilRoute = _authenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedPenggunaanBahanKimiaRoute =
  _authenticatedPenggunaanBahanKimiaRouteImport.update({
    id: '/penggunaan-bahan-kimia',
    path: '/penggunaan-bahan-kimia',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPencatatanHarianRoute =
  _authenticatedPencatatanHarianRouteImport.update({
    id: '/pencatatan-harian',
    path: '/pencatatan-harian',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedLogAktivitasRoute =
  _authenticatedLogAktivitasRouteImport.update({
    id: '/log-aktivitas',
    path: '/log-aktivitas',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedListDataRoute = _authenticatedListDataRouteImport.update({
  id: '/list-data',
  path: '/list-data',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedJadwalRoute = _authenticatedJadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedGantiPasswordRoute =
  _authenticatedGantiPasswordRouteImport.update({
    id: '/ganti-password',
    path: '/ganti-password',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedDashboardRoute = _authenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedComingSoonRoute =
  _authenticatedComingSoonRouteImport.update({
    id: '/coming-soon',
    path: '/coming-soon',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedBahanKimiaRoute =
  _authenticatedBahanKimiaRouteImport.update({
    id: '/bahan-kimia',
    path: '/bahan-kimia',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedAnomaliRoute = _authenticatedAnomaliRouteImport.update({
  id: '/anomali',
  path: '/anomali',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedFormAnomaliRoute =
  _authenticatedFormAnomaliRouteImport.update({
    id: '/form/anomali',
    path: '/form/anomali',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPagesDetailKodeRoute =
  _authenticatedPagesDetailKodeRouteImport.update({
    id: '/pages/detail/$kode',
    path: '/pages/detail/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPagesDetailWtpDebtKodeRoute =
  _authenticatedPagesDetailWtpDebtKodeRouteImport.update({
    id: '/pages/detail-wtp-debt/$kode',
    path: '/pages/detail-wtp-debt/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPagesDetailSgaiKodeRoute =
  _authenticatedPagesDetailSgaiKodeRouteImport.update({
    id: '/pages/detail-sgai/$kode',
    path: '/pages/detail-sgai/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPagesDetailRsvKodeRoute =
  _authenticatedPagesDetailRsvKodeRouteImport.update({
    id: '/pages/detail-rsv/$kode',
    path: '/pages/detail-rsv/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPagesDetailPompAtmKodeRoute =
  _authenticatedPagesDetailPompAtmKodeRouteImport.update({
    id: '/pages/detail-pomp-atm/$kode',
    path: '/pages/detail-pomp-atm/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPagesDetailPompAmpKodeRoute =
  _authenticatedPagesDetailPompAmpKodeRouteImport.update({
    id: '/pages/detail-pomp-amp/$kode',
    path: '/pages/detail-pomp-amp/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPagesDetailPlnKodeRoute =
  _authenticatedPagesDetailPlnKodeRouteImport.update({
    id: '/pages/detail-pln/$kode',
    path: '/pages/detail-pln/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPagesDetailPakaiKntrKodeRoute =
  _authenticatedPagesDetailPakaiKntrKodeRouteImport.update({
    id: '/pages/detail-pakai-kntr/$kode',
    path: '/pages/detail-pakai-kntr/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPagesDetailMtrHrsKodeRoute =
  _authenticatedPagesDetailMtrHrsKodeRouteImport.update({
    id: '/pages/detail-mtr-hrs/$kode',
    path: '/pages/detail-mtr-hrs/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPagesDetailKwlUaKodeRoute =
  _authenticatedPagesDetailKwlUaKodeRouteImport.update({
    id: '/pages/detail-kwl-ua/$kode',
    path: '/pages/detail-kwl-ua/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPagesDetailKimiaKodeRoute =
  _authenticatedPagesDetailKimiaKodeRouteImport.update({
    id: '/pages/detail-kimia/$kode',
    path: '/pages/detail-kimia/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPagesDetailGnstKodeRoute =
  _authenticatedPagesDetailGnstKodeRouteImport.update({
    id: '/pages/detail-gnst/$kode',
    path: '/pages/detail-gnst/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPagesDetailDosisKodeRoute =
  _authenticatedPagesDetailDosisKodeRouteImport.update({
    id: '/pages/detail-dosis/$kode',
    path: '/pages/detail-dosis/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPagesDetailCuciKodeRoute =
  _authenticatedPagesDetailCuciKodeRouteImport.update({
    id: '/pages/detail-cuci/$kode',
    path: '/pages/detail-cuci/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedPagesDetailCpltKodeRoute =
  _authenticatedPagesDetailCpltKodeRouteImport.update({
    id: '/pages/detail-cplt/$kode',
    path: '/pages/detail-cplt/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedFormWtpDebtIdRoute =
  _authenticatedFormWtpDebtIdRouteImport.update({
    id: '/form/wtp-debt/$id',
    path: '/form/wtp-debt/$id',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedFormSgaiIdRoute =
  _authenticatedFormSgaiIdRouteImport.update({
    id: '/form/sgai/$id',
    path: '/form/sgai/$id',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedFormRsvIdRoute = _authenticatedFormRsvIdRouteImport.update({
  id: '/form/rsv/$id',
  path: '/form/rsv/$id',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedFormPompAtmIdRoute =
  _authenticatedFormPompAtmIdRouteImport.update({
    id: '/form/pomp-atm/$id',
    path: '/form/pomp-atm/$id',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedFormPompAmpIdRoute =
  _authenticatedFormPompAmpIdRouteImport.update({
    id: '/form/pomp-amp/$id',
    path: '/form/pomp-amp/$id',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedFormPenggunaanBahanKimiaKodeRoute =
  _authenticatedFormPenggunaanBahanKimiaKodeRouteImport.update({
    id: '/form/penggunaan-bahan-kimia/$kode',
    path: '/form/penggunaan-bahan-kimia/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedFormPemakaianKantorIdRoute =
  _authenticatedFormPemakaianKantorIdRouteImport.update({
    id: '/form/pemakaian-kantor/$id',
    path: '/form/pemakaian-kantor/$id',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedFormPakaiKantorKodeRoute =
  _authenticatedFormPakaiKantorKodeRouteImport.update({
    id: '/form/pakai-kantor/$kode',
    path: '/form/pakai-kantor/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedFormMeterIdRoute =
  _authenticatedFormMeterIdRouteImport.update({
    id: '/form/meter/$id',
    path: '/form/meter/$id',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedFormMeterPlnIdRoute =
  _authenticatedFormMeterPlnIdRouteImport.update({
    id: '/form/meter-pln/$id',
    path: '/form/meter-pln/$id',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedFormKwluaIdRoute =
  _authenticatedFormKwluaIdRouteImport.update({
    id: '/form/kwlua/$id',
    path: '/form/kwlua/$id',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedFormKimiaIdRoute =
  _authenticatedFormKimiaIdRouteImport.update({
    id: '/form/kimia/$id',
    path: '/form/kimia/$id',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedFormHoursPompaKodeRoute =
  _authenticatedFormHoursPompaKodeRouteImport.update({
    id: '/form/hours-pompa/$kode',
    path: '/form/hours-pompa/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedFormGensetKodeRoute =
  _authenticatedFormGensetKodeRouteImport.update({
    id: '/form/genset/$kode',
    path: '/form/genset/$kode',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedFormDosisIdRoute =
  _authenticatedFormDosisIdRouteImport.update({
    id: '/form/dosis/$id',
    path: '/form/dosis/$id',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedFormCuciIdRoute =
  _authenticatedFormCuciIdRouteImport.update({
    id: '/form/cuci/$id',
    path: '/form/cuci/$id',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedFormCipoletyIdRoute =
  _authenticatedFormCipoletyIdRouteImport.update({
    id: '/form/cipolety/$id',
    path: '/form/cipolety/$id',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedFormCuciInputJenisRoute =
  _authenticatedFormCuciInputJenisRouteImport.update({
    id: '/form/cuci/input/$jenis',
    path: '/form/cuci/input/$jenis',
    getParentRoute: () => _authenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kamera': typeof KameraRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/anomali': typeof _authenticatedAnomaliRoute
  '/bahan-kimia': typeof _authenticatedBahanKimiaRoute
  '/coming-soon': typeof _authenticatedComingSoonRoute
  '/dashboard': typeof _authenticatedDashboardRoute
  '/ganti-password': typeof _authenticatedGantiPasswordRoute
  '/jadwal': typeof _authenticatedJadwalRoute
  '/list-data': typeof _authenticatedListDataRoute
  '/log-aktivitas': typeof _authenticatedLogAktivitasRoute
  '/pencatatan-harian': typeof _authenticatedPencatatanHarianRoute
  '/penggunaan-bahan-kimia': typeof _authenticatedPenggunaanBahanKimiaRoute
  '/profil': typeof _authenticatedProfilRoute
  '/form/anomali': typeof _authenticatedFormAnomaliRoute
  '/form/cipolety/$id': typeof _authenticatedFormCipoletyIdRoute
  '/form/cuci/$id': typeof _authenticatedFormCuciIdRoute
  '/form/dosis/$id': typeof _authenticatedFormDosisIdRoute
  '/form/genset/$kode': typeof _authenticatedFormGensetKodeRoute
  '/form/hours-pompa/$kode': typeof _authenticatedFormHoursPompaKodeRoute
  '/form/kimia/$id': typeof _authenticatedFormKimiaIdRoute
  '/form/kwlua/$id': typeof _authenticatedFormKwluaIdRoute
  '/form/meter-pln/$id': typeof _authenticatedFormMeterPlnIdRoute
  '/form/meter/$id': typeof _authenticatedFormMeterIdRoute
  '/form/pakai-kantor/$kode': typeof _authenticatedFormPakaiKantorKodeRoute
  '/form/pemakaian-kantor/$id': typeof _authenticatedFormPemakaianKantorIdRoute
  '/form/penggunaan-bahan-kimia/$kode': typeof _authenticatedFormPenggunaanBahanKimiaKodeRoute
  '/form/pomp-amp/$id': typeof _authenticatedFormPompAmpIdRoute
  '/form/pomp-atm/$id': typeof _authenticatedFormPompAtmIdRoute
  '/form/rsv/$id': typeof _authenticatedFormRsvIdRoute
  '/form/sgai/$id': typeof _authenticatedFormSgaiIdRoute
  '/form/wtp-debt/$id': typeof _authenticatedFormWtpDebtIdRoute
  '/pages/detail-cplt/$kode': typeof _authenticatedPagesDetailCpltKodeRoute
  '/pages/detail-cuci/$kode': typeof _authenticatedPagesDetailCuciKodeRoute
  '/pages/detail-dosis/$kode': typeof _authenticatedPagesDetailDosisKodeRoute
  '/pages/detail-gnst/$kode': typeof _authenticatedPagesDetailGnstKodeRoute
  '/pages/detail-kimia/$kode': typeof _authenticatedPagesDetailKimiaKodeRoute
  '/pages/detail-kwl-ua/$kode': typeof _authenticatedPagesDetailKwlUaKodeRoute
  '/pages/detail-mtr-hrs/$kode': typeof _authenticatedPagesDetailMtrHrsKodeRoute
  '/pages/detail-pakai-kntr/$kode': typeof _authenticatedPagesDetailPakaiKntrKodeRoute
  '/pages/detail-pln/$kode': typeof _authenticatedPagesDetailPlnKodeRoute
  '/pages/detail-pomp-amp/$kode': typeof _authenticatedPagesDetailPompAmpKodeRoute
  '/pages/detail-pomp-atm/$kode': typeof _authenticatedPagesDetailPompAtmKodeRoute
  '/pages/detail-rsv/$kode': typeof _authenticatedPagesDetailRsvKodeRoute
  '/pages/detail-sgai/$kode': typeof _authenticatedPagesDetailSgaiKodeRoute
  '/pages/detail-wtp-debt/$kode': typeof _authenticatedPagesDetailWtpDebtKodeRoute
  '/pages/detail/$kode': typeof _authenticatedPagesDetailKodeRoute
  '/form/cuci/input/$jenis': typeof _authenticatedFormCuciInputJenisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kamera': typeof KameraRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/anomali': typeof _authenticatedAnomaliRoute
  '/bahan-kimia': typeof _authenticatedBahanKimiaRoute
  '/coming-soon': typeof _authenticatedComingSoonRoute
  '/dashboard': typeof _authenticatedDashboardRoute
  '/ganti-password': typeof _authenticatedGantiPasswordRoute
  '/jadwal': typeof _authenticatedJadwalRoute
  '/list-data': typeof _authenticatedListDataRoute
  '/log-aktivitas': typeof _authenticatedLogAktivitasRoute
  '/pencatatan-harian': typeof _authenticatedPencatatanHarianRoute
  '/penggunaan-bahan-kimia': typeof _authenticatedPenggunaanBahanKimiaRoute
  '/profil': typeof _authenticatedProfilRoute
  '/form/anomali': typeof _authenticatedFormAnomaliRoute
  '/form/cipolety/$id': typeof _authenticatedFormCipoletyIdRoute
  '/form/cuci/$id': typeof _authenticatedFormCuciIdRoute
  '/form/dosis/$id': typeof _authenticatedFormDosisIdRoute
  '/form/genset/$kode': typeof _authenticatedFormGensetKodeRoute
  '/form/hours-pompa/$kode': typeof _authenticatedFormHoursPompaKodeRoute
  '/form/kimia/$id': typeof _authenticatedFormKimiaIdRoute
  '/form/kwlua/$id': typeof _authenticatedFormKwluaIdRoute
  '/form/meter-pln/$id': typeof _authenticatedFormMeterPlnIdRoute
  '/form/meter/$id': typeof _authenticatedFormMeterIdRoute
  '/form/pakai-kantor/$kode': typeof _authenticatedFormPakaiKantorKodeRoute
  '/form/pemakaian-kantor/$id': typeof _authenticatedFormPemakaianKantorIdRoute
  '/form/penggunaan-bahan-kimia/$kode': typeof _authenticatedFormPenggunaanBahanKimiaKodeRoute
  '/form/pomp-amp/$id': typeof _authenticatedFormPompAmpIdRoute
  '/form/pomp-atm/$id': typeof _authenticatedFormPompAtmIdRoute
  '/form/rsv/$id': typeof _authenticatedFormRsvIdRoute
  '/form/sgai/$id': typeof _authenticatedFormSgaiIdRoute
  '/form/wtp-debt/$id': typeof _authenticatedFormWtpDebtIdRoute
  '/pages/detail-cplt/$kode': typeof _authenticatedPagesDetailCpltKodeRoute
  '/pages/detail-cuci/$kode': typeof _authenticatedPagesDetailCuciKodeRoute
  '/pages/detail-dosis/$kode': typeof _authenticatedPagesDetailDosisKodeRoute
  '/pages/detail-gnst/$kode': typeof _authenticatedPagesDetailGnstKodeRoute
  '/pages/detail-kimia/$kode': typeof _authenticatedPagesDetailKimiaKodeRoute
  '/pages/detail-kwl-ua/$kode': typeof _authenticatedPagesDetailKwlUaKodeRoute
  '/pages/detail-mtr-hrs/$kode': typeof _authenticatedPagesDetailMtrHrsKodeRoute
  '/pages/detail-pakai-kntr/$kode': typeof _authenticatedPagesDetailPakaiKntrKodeRoute
  '/pages/detail-pln/$kode': typeof _authenticatedPagesDetailPlnKodeRoute
  '/pages/detail-pomp-amp/$kode': typeof _authenticatedPagesDetailPompAmpKodeRoute
  '/pages/detail-pomp-atm/$kode': typeof _authenticatedPagesDetailPompAtmKodeRoute
  '/pages/detail-rsv/$kode': typeof _authenticatedPagesDetailRsvKodeRoute
  '/pages/detail-sgai/$kode': typeof _authenticatedPagesDetailSgaiKodeRoute
  '/pages/detail-wtp-debt/$kode': typeof _authenticatedPagesDetailWtpDebtKodeRoute
  '/pages/detail/$kode': typeof _authenticatedPagesDetailKodeRoute
  '/form/cuci/input/$jenis': typeof _authenticatedFormCuciInputJenisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__authenticated': typeof _authenticatedRouteWithChildren
  '/kamera': typeof KameraRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/__authenticated/anomali': typeof _authenticatedAnomaliRoute
  '/__authenticated/bahan-kimia': typeof _authenticatedBahanKimiaRoute
  '/__authenticated/coming-soon': typeof _authenticatedComingSoonRoute
  '/__authenticated/dashboard': typeof _authenticatedDashboardRoute
  '/__authenticated/ganti-password': typeof _authenticatedGantiPasswordRoute
  '/__authenticated/jadwal': typeof _authenticatedJadwalRoute
  '/__authenticated/list-data': typeof _authenticatedListDataRoute
  '/__authenticated/log-aktivitas': typeof _authenticatedLogAktivitasRoute
  '/__authenticated/pencatatan-harian': typeof _authenticatedPencatatanHarianRoute
  '/__authenticated/penggunaan-bahan-kimia': typeof _authenticatedPenggunaanBahanKimiaRoute
  '/__authenticated/profil': typeof _authenticatedProfilRoute
  '/__authenticated/form/anomali': typeof _authenticatedFormAnomaliRoute
  '/__authenticated/form/cipolety/$id': typeof _authenticatedFormCipoletyIdRoute
  '/__authenticated/form/cuci/$id': typeof _authenticatedFormCuciIdRoute
  '/__authenticated/form/dosis/$id': typeof _authenticatedFormDosisIdRoute
  '/__authenticated/form/genset/$kode': typeof _authenticatedFormGensetKodeRoute
  '/__authenticated/form/hours-pompa/$kode': typeof _authenticatedFormHoursPompaKodeRoute
  '/__authenticated/form/kimia/$id': typeof _authenticatedFormKimiaIdRoute
  '/__authenticated/form/kwlua/$id': typeof _authenticatedFormKwluaIdRoute
  '/__authenticated/form/meter-pln/$id': typeof _authenticatedFormMeterPlnIdRoute
  '/__authenticated/form/meter/$id': typeof _authenticatedFormMeterIdRoute
  '/__authenticated/form/pakai-kantor/$kode': typeof _authenticatedFormPakaiKantorKodeRoute
  '/__authenticated/form/pemakaian-kantor/$id': typeof _authenticatedFormPemakaianKantorIdRoute
  '/__authenticated/form/penggunaan-bahan-kimia/$kode': typeof _authenticatedFormPenggunaanBahanKimiaKodeRoute
  '/__authenticated/form/pomp-amp/$id': typeof _authenticatedFormPompAmpIdRoute
  '/__authenticated/form/pomp-atm/$id': typeof _authenticatedFormPompAtmIdRoute
  '/__authenticated/form/rsv/$id': typeof _authenticatedFormRsvIdRoute
  '/__authenticated/form/sgai/$id': typeof _authenticatedFormSgaiIdRoute
  '/__authenticated/form/wtp-debt/$id': typeof _authenticatedFormWtpDebtIdRoute
  '/__authenticated/pages/detail-cplt/$kode': typeof _authenticatedPagesDetailCpltKodeRoute
  '/__authenticated/pages/detail-cuci/$kode': typeof _authenticatedPagesDetailCuciKodeRoute
  '/__authenticated/pages/detail-dosis/$kode': typeof _authenticatedPagesDetailDosisKodeRoute
  '/__authenticated/pages/detail-gnst/$kode': typeof _authenticatedPagesDetailGnstKodeRoute
  '/__authenticated/pages/detail-kimia/$kode': typeof _authenticatedPagesDetailKimiaKodeRoute
  '/__authenticated/pages/detail-kwl-ua/$kode': typeof _authenticatedPagesDetailKwlUaKodeRoute
  '/__authenticated/pages/detail-mtr-hrs/$kode': typeof _authenticatedPagesDetailMtrHrsKodeRoute
  '/__authenticated/pages/detail-pakai-kntr/$kode': typeof _authenticatedPagesDetailPakaiKntrKodeRoute
  '/__authenticated/pages/detail-pln/$kode': typeof _authenticatedPagesDetailPlnKodeRoute
  '/__authenticated/pages/detail-pomp-amp/$kode': typeof _authenticatedPagesDetailPompAmpKodeRoute
  '/__authenticated/pages/detail-pomp-atm/$kode': typeof _authenticatedPagesDetailPompAtmKodeRoute
  '/__authenticated/pages/detail-rsv/$kode': typeof _authenticatedPagesDetailRsvKodeRoute
  '/__authenticated/pages/detail-sgai/$kode': typeof _authenticatedPagesDetailSgaiKodeRoute
  '/__authenticated/pages/detail-wtp-debt/$kode': typeof _authenticatedPagesDetailWtpDebtKodeRoute
  '/__authenticated/pages/detail/$kode': typeof _authenticatedPagesDetailKodeRoute
  '/__authenticated/form/cuci/input/$jenis': typeof _authenticatedFormCuciInputJenisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kamera'
    | '/login'
    | '/not-found'
    | '/anomali'
    | '/bahan-kimia'
    | '/coming-soon'
    | '/dashboard'
    | '/ganti-password'
    | '/jadwal'
    | '/list-data'
    | '/log-aktivitas'
    | '/pencatatan-harian'
    | '/penggunaan-bahan-kimia'
    | '/profil'
    | '/form/anomali'
    | '/form/cipolety/$id'
    | '/form/cuci/$id'
    | '/form/dosis/$id'
    | '/form/genset/$kode'
    | '/form/hours-pompa/$kode'
    | '/form/kimia/$id'
    | '/form/kwlua/$id'
    | '/form/meter-pln/$id'
    | '/form/meter/$id'
    | '/form/pakai-kantor/$kode'
    | '/form/pemakaian-kantor/$id'
    | '/form/penggunaan-bahan-kimia/$kode'
    | '/form/pomp-amp/$id'
    | '/form/pomp-atm/$id'
    | '/form/rsv/$id'
    | '/form/sgai/$id'
    | '/form/wtp-debt/$id'
    | '/pages/detail-cplt/$kode'
    | '/pages/detail-cuci/$kode'
    | '/pages/detail-dosis/$kode'
    | '/pages/detail-gnst/$kode'
    | '/pages/detail-kimia/$kode'
    | '/pages/detail-kwl-ua/$kode'
    | '/pages/detail-mtr-hrs/$kode'
    | '/pages/detail-pakai-kntr/$kode'
    | '/pages/detail-pln/$kode'
    | '/pages/detail-pomp-amp/$kode'
    | '/pages/detail-pomp-atm/$kode'
    | '/pages/detail-rsv/$kode'
    | '/pages/detail-sgai/$kode'
    | '/pages/detail-wtp-debt/$kode'
    | '/pages/detail/$kode'
    | '/form/cuci/input/$jenis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kamera'
    | '/login'
    | '/not-found'
    | '/anomali'
    | '/bahan-kimia'
    | '/coming-soon'
    | '/dashboard'
    | '/ganti-password'
    | '/jadwal'
    | '/list-data'
    | '/log-aktivitas'
    | '/pencatatan-harian'
    | '/penggunaan-bahan-kimia'
    | '/profil'
    | '/form/anomali'
    | '/form/cipolety/$id'
    | '/form/cuci/$id'
    | '/form/dosis/$id'
    | '/form/genset/$kode'
    | '/form/hours-pompa/$kode'
    | '/form/kimia/$id'
    | '/form/kwlua/$id'
    | '/form/meter-pln/$id'
    | '/form/meter/$id'
    | '/form/pakai-kantor/$kode'
    | '/form/pemakaian-kantor/$id'
    | '/form/penggunaan-bahan-kimia/$kode'
    | '/form/pomp-amp/$id'
    | '/form/pomp-atm/$id'
    | '/form/rsv/$id'
    | '/form/sgai/$id'
    | '/form/wtp-debt/$id'
    | '/pages/detail-cplt/$kode'
    | '/pages/detail-cuci/$kode'
    | '/pages/detail-dosis/$kode'
    | '/pages/detail-gnst/$kode'
    | '/pages/detail-kimia/$kode'
    | '/pages/detail-kwl-ua/$kode'
    | '/pages/detail-mtr-hrs/$kode'
    | '/pages/detail-pakai-kntr/$kode'
    | '/pages/detail-pln/$kode'
    | '/pages/detail-pomp-amp/$kode'
    | '/pages/detail-pomp-atm/$kode'
    | '/pages/detail-rsv/$kode'
    | '/pages/detail-sgai/$kode'
    | '/pages/detail-wtp-debt/$kode'
    | '/pages/detail/$kode'
    | '/form/cuci/input/$jenis'
  id:
    | '__root__'
    | '/'
    | '/__authenticated'
    | '/kamera'
    | '/login'
    | '/not-found'
    | '/__authenticated/anomali'
    | '/__authenticated/bahan-kimia'
    | '/__authenticated/coming-soon'
    | '/__authenticated/dashboard'
    | '/__authenticated/ganti-password'
    | '/__authenticated/jadwal'
    | '/__authenticated/list-data'
    | '/__authenticated/log-aktivitas'
    | '/__authenticated/pencatatan-harian'
    | '/__authenticated/penggunaan-bahan-kimia'
    | '/__authenticated/profil'
    | '/__authenticated/form/anomali'
    | '/__authenticated/form/cipolety/$id'
    | '/__authenticated/form/cuci/$id'
    | '/__authenticated/form/dosis/$id'
    | '/__authenticated/form/genset/$kode'
    | '/__authenticated/form/hours-pompa/$kode'
    | '/__authenticated/form/kimia/$id'
    | '/__authenticated/form/kwlua/$id'
    | '/__authenticated/form/meter-pln/$id'
    | '/__authenticated/form/meter/$id'
    | '/__authenticated/form/pakai-kantor/$kode'
    | '/__authenticated/form/pemakaian-kantor/$id'
    | '/__authenticated/form/penggunaan-bahan-kimia/$kode'
    | '/__authenticated/form/pomp-amp/$id'
    | '/__authenticated/form/pomp-atm/$id'
    | '/__authenticated/form/rsv/$id'
    | '/__authenticated/form/sgai/$id'
    | '/__authenticated/form/wtp-debt/$id'
    | '/__authenticated/pages/detail-cplt/$kode'
    | '/__authenticated/pages/detail-cuci/$kode'
    | '/__authenticated/pages/detail-dosis/$kode'
    | '/__authenticated/pages/detail-gnst/$kode'
    | '/__authenticated/pages/detail-kimia/$kode'
    | '/__authenticated/pages/detail-kwl-ua/$kode'
    | '/__authenticated/pages/detail-mtr-hrs/$kode'
    | '/__authenticated/pages/detail-pakai-kntr/$kode'
    | '/__authenticated/pages/detail-pln/$kode'
    | '/__authenticated/pages/detail-pomp-amp/$kode'
    | '/__authenticated/pages/detail-pomp-atm/$kode'
    | '/__authenticated/pages/detail-rsv/$kode'
    | '/__authenticated/pages/detail-sgai/$kode'
    | '/__authenticated/pages/detail-wtp-debt/$kode'
    | '/__authenticated/pages/detail/$kode'
    | '/__authenticated/form/cuci/input/$jenis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _authenticatedRoute: typeof _authenticatedRouteWithChildren
  KameraRoute: typeof KameraRoute
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamera': {
      id: '/kamera'
      path: '/kamera'
      fullPath: '/kamera'
      preLoaderRoute: typeof KameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated': {
      id: '/__authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated/profil': {
      id: '/__authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof _authenticatedProfilRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/penggunaan-bahan-kimia': {
      id: '/__authenticated/penggunaan-bahan-kimia'
      path: '/penggunaan-bahan-kimia'
      fullPath: '/penggunaan-bahan-kimia'
      preLoaderRoute: typeof _authenticatedPenggunaanBahanKimiaRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/pencatatan-harian': {
      id: '/__authenticated/pencatatan-harian'
      path: '/pencatatan-harian'
      fullPath: '/pencatatan-harian'
      preLoaderRoute: typeof _authenticatedPencatatanHarianRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/log-aktivitas': {
      id: '/__authenticated/log-aktivitas'
      path: '/log-aktivitas'
      fullPath: '/log-aktivitas'
      preLoaderRoute: typeof _authenticatedLogAktivitasRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/list-data': {
      id: '/__authenticated/list-data'
      path: '/list-data'
      fullPath: '/list-data'
      preLoaderRoute: typeof _authenticatedListDataRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/jadwal': {
      id: '/__authenticated/jadwal'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof _authenticatedJadwalRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/ganti-password': {
      id: '/__authenticated/ganti-password'
      path: '/ganti-password'
      fullPath: '/ganti-password'
      preLoaderRoute: typeof _authenticatedGantiPasswordRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/dashboard': {
      id: '/__authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof _authenticatedDashboardRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/coming-soon': {
      id: '/__authenticated/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof _authenticatedComingSoonRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/bahan-kimia': {
      id: '/__authenticated/bahan-kimia'
      path: '/bahan-kimia'
      fullPath: '/bahan-kimia'
      preLoaderRoute: typeof _authenticatedBahanKimiaRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/anomali': {
      id: '/__authenticated/anomali'
      path: '/anomali'
      fullPath: '/anomali'
      preLoaderRoute: typeof _authenticatedAnomaliRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/anomali': {
      id: '/__authenticated/form/anomali'
      path: '/form/anomali'
      fullPath: '/form/anomali'
      preLoaderRoute: typeof _authenticatedFormAnomaliRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/pages/detail/$kode': {
      id: '/__authenticated/pages/detail/$kode'
      path: '/pages/detail/$kode'
      fullPath: '/pages/detail/$kode'
      preLoaderRoute: typeof _authenticatedPagesDetailKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/pages/detail-wtp-debt/$kode': {
      id: '/__authenticated/pages/detail-wtp-debt/$kode'
      path: '/pages/detail-wtp-debt/$kode'
      fullPath: '/pages/detail-wtp-debt/$kode'
      preLoaderRoute: typeof _authenticatedPagesDetailWtpDebtKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/pages/detail-sgai/$kode': {
      id: '/__authenticated/pages/detail-sgai/$kode'
      path: '/pages/detail-sgai/$kode'
      fullPath: '/pages/detail-sgai/$kode'
      preLoaderRoute: typeof _authenticatedPagesDetailSgaiKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/pages/detail-rsv/$kode': {
      id: '/__authenticated/pages/detail-rsv/$kode'
      path: '/pages/detail-rsv/$kode'
      fullPath: '/pages/detail-rsv/$kode'
      preLoaderRoute: typeof _authenticatedPagesDetailRsvKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/pages/detail-pomp-atm/$kode': {
      id: '/__authenticated/pages/detail-pomp-atm/$kode'
      path: '/pages/detail-pomp-atm/$kode'
      fullPath: '/pages/detail-pomp-atm/$kode'
      preLoaderRoute: typeof _authenticatedPagesDetailPompAtmKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/pages/detail-pomp-amp/$kode': {
      id: '/__authenticated/pages/detail-pomp-amp/$kode'
      path: '/pages/detail-pomp-amp/$kode'
      fullPath: '/pages/detail-pomp-amp/$kode'
      preLoaderRoute: typeof _authenticatedPagesDetailPompAmpKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/pages/detail-pln/$kode': {
      id: '/__authenticated/pages/detail-pln/$kode'
      path: '/pages/detail-pln/$kode'
      fullPath: '/pages/detail-pln/$kode'
      preLoaderRoute: typeof _authenticatedPagesDetailPlnKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/pages/detail-pakai-kntr/$kode': {
      id: '/__authenticated/pages/detail-pakai-kntr/$kode'
      path: '/pages/detail-pakai-kntr/$kode'
      fullPath: '/pages/detail-pakai-kntr/$kode'
      preLoaderRoute: typeof _authenticatedPagesDetailPakaiKntrKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/pages/detail-mtr-hrs/$kode': {
      id: '/__authenticated/pages/detail-mtr-hrs/$kode'
      path: '/pages/detail-mtr-hrs/$kode'
      fullPath: '/pages/detail-mtr-hrs/$kode'
      preLoaderRoute: typeof _authenticatedPagesDetailMtrHrsKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/pages/detail-kwl-ua/$kode': {
      id: '/__authenticated/pages/detail-kwl-ua/$kode'
      path: '/pages/detail-kwl-ua/$kode'
      fullPath: '/pages/detail-kwl-ua/$kode'
      preLoaderRoute: typeof _authenticatedPagesDetailKwlUaKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/pages/detail-kimia/$kode': {
      id: '/__authenticated/pages/detail-kimia/$kode'
      path: '/pages/detail-kimia/$kode'
      fullPath: '/pages/detail-kimia/$kode'
      preLoaderRoute: typeof _authenticatedPagesDetailKimiaKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/pages/detail-gnst/$kode': {
      id: '/__authenticated/pages/detail-gnst/$kode'
      path: '/pages/detail-gnst/$kode'
      fullPath: '/pages/detail-gnst/$kode'
      preLoaderRoute: typeof _authenticatedPagesDetailGnstKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/pages/detail-dosis/$kode': {
      id: '/__authenticated/pages/detail-dosis/$kode'
      path: '/pages/detail-dosis/$kode'
      fullPath: '/pages/detail-dosis/$kode'
      preLoaderRoute: typeof _authenticatedPagesDetailDosisKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/pages/detail-cuci/$kode': {
      id: '/__authenticated/pages/detail-cuci/$kode'
      path: '/pages/detail-cuci/$kode'
      fullPath: '/pages/detail-cuci/$kode'
      preLoaderRoute: typeof _authenticatedPagesDetailCuciKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/pages/detail-cplt/$kode': {
      id: '/__authenticated/pages/detail-cplt/$kode'
      path: '/pages/detail-cplt/$kode'
      fullPath: '/pages/detail-cplt/$kode'
      preLoaderRoute: typeof _authenticatedPagesDetailCpltKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/wtp-debt/$id': {
      id: '/__authenticated/form/wtp-debt/$id'
      path: '/form/wtp-debt/$id'
      fullPath: '/form/wtp-debt/$id'
      preLoaderRoute: typeof _authenticatedFormWtpDebtIdRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/sgai/$id': {
      id: '/__authenticated/form/sgai/$id'
      path: '/form/sgai/$id'
      fullPath: '/form/sgai/$id'
      preLoaderRoute: typeof _authenticatedFormSgaiIdRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/rsv/$id': {
      id: '/__authenticated/form/rsv/$id'
      path: '/form/rsv/$id'
      fullPath: '/form/rsv/$id'
      preLoaderRoute: typeof _authenticatedFormRsvIdRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/pomp-atm/$id': {
      id: '/__authenticated/form/pomp-atm/$id'
      path: '/form/pomp-atm/$id'
      fullPath: '/form/pomp-atm/$id'
      preLoaderRoute: typeof _authenticatedFormPompAtmIdRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/pomp-amp/$id': {
      id: '/__authenticated/form/pomp-amp/$id'
      path: '/form/pomp-amp/$id'
      fullPath: '/form/pomp-amp/$id'
      preLoaderRoute: typeof _authenticatedFormPompAmpIdRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/penggunaan-bahan-kimia/$kode': {
      id: '/__authenticated/form/penggunaan-bahan-kimia/$kode'
      path: '/form/penggunaan-bahan-kimia/$kode'
      fullPath: '/form/penggunaan-bahan-kimia/$kode'
      preLoaderRoute: typeof _authenticatedFormPenggunaanBahanKimiaKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/pemakaian-kantor/$id': {
      id: '/__authenticated/form/pemakaian-kantor/$id'
      path: '/form/pemakaian-kantor/$id'
      fullPath: '/form/pemakaian-kantor/$id'
      preLoaderRoute: typeof _authenticatedFormPemakaianKantorIdRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/pakai-kantor/$kode': {
      id: '/__authenticated/form/pakai-kantor/$kode'
      path: '/form/pakai-kantor/$kode'
      fullPath: '/form/pakai-kantor/$kode'
      preLoaderRoute: typeof _authenticatedFormPakaiKantorKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/meter/$id': {
      id: '/__authenticated/form/meter/$id'
      path: '/form/meter/$id'
      fullPath: '/form/meter/$id'
      preLoaderRoute: typeof _authenticatedFormMeterIdRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/meter-pln/$id': {
      id: '/__authenticated/form/meter-pln/$id'
      path: '/form/meter-pln/$id'
      fullPath: '/form/meter-pln/$id'
      preLoaderRoute: typeof _authenticatedFormMeterPlnIdRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/kwlua/$id': {
      id: '/__authenticated/form/kwlua/$id'
      path: '/form/kwlua/$id'
      fullPath: '/form/kwlua/$id'
      preLoaderRoute: typeof _authenticatedFormKwluaIdRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/kimia/$id': {
      id: '/__authenticated/form/kimia/$id'
      path: '/form/kimia/$id'
      fullPath: '/form/kimia/$id'
      preLoaderRoute: typeof _authenticatedFormKimiaIdRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/hours-pompa/$kode': {
      id: '/__authenticated/form/hours-pompa/$kode'
      path: '/form/hours-pompa/$kode'
      fullPath: '/form/hours-pompa/$kode'
      preLoaderRoute: typeof _authenticatedFormHoursPompaKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/genset/$kode': {
      id: '/__authenticated/form/genset/$kode'
      path: '/form/genset/$kode'
      fullPath: '/form/genset/$kode'
      preLoaderRoute: typeof _authenticatedFormGensetKodeRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/dosis/$id': {
      id: '/__authenticated/form/dosis/$id'
      path: '/form/dosis/$id'
      fullPath: '/form/dosis/$id'
      preLoaderRoute: typeof _authenticatedFormDosisIdRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/cuci/$id': {
      id: '/__authenticated/form/cuci/$id'
      path: '/form/cuci/$id'
      fullPath: '/form/cuci/$id'
      preLoaderRoute: typeof _authenticatedFormCuciIdRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/cipolety/$id': {
      id: '/__authenticated/form/cipolety/$id'
      path: '/form/cipolety/$id'
      fullPath: '/form/cipolety/$id'
      preLoaderRoute: typeof _authenticatedFormCipoletyIdRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/form/cuci/input/$jenis': {
      id: '/__authenticated/form/cuci/input/$jenis'
      path: '/form/cuci/input/$jenis'
      fullPath: '/form/cuci/input/$jenis'
      preLoaderRoute: typeof _authenticatedFormCuciInputJenisRouteImport
      parentRoute: typeof _authenticatedRoute
    }
  }
}

interface _authenticatedRouteChildren {
  _authenticatedAnomaliRoute: typeof _authenticatedAnomaliRoute
  _authenticatedBahanKimiaRoute: typeof _authenticatedBahanKimiaRoute
  _authenticatedComingSoonRoute: typeof _authenticatedComingSoonRoute
  _authenticatedDashboardRoute: typeof _authenticatedDashboardRoute
  _authenticatedGantiPasswordRoute: typeof _authenticatedGantiPasswordRoute
  _authenticatedJadwalRoute: typeof _authenticatedJadwalRoute
  _authenticatedListDataRoute: typeof _authenticatedListDataRoute
  _authenticatedLogAktivitasRoute: typeof _authenticatedLogAktivitasRoute
  _authenticatedPencatatanHarianRoute: typeof _authenticatedPencatatanHarianRoute
  _authenticatedPenggunaanBahanKimiaRoute: typeof _authenticatedPenggunaanBahanKimiaRoute
  _authenticatedProfilRoute: typeof _authenticatedProfilRoute
  _authenticatedFormAnomaliRoute: typeof _authenticatedFormAnomaliRoute
  _authenticatedFormCipoletyIdRoute: typeof _authenticatedFormCipoletyIdRoute
  _authenticatedFormCuciIdRoute: typeof _authenticatedFormCuciIdRoute
  _authenticatedFormDosisIdRoute: typeof _authenticatedFormDosisIdRoute
  _authenticatedFormGensetKodeRoute: typeof _authenticatedFormGensetKodeRoute
  _authenticatedFormHoursPompaKodeRoute: typeof _authenticatedFormHoursPompaKodeRoute
  _authenticatedFormKimiaIdRoute: typeof _authenticatedFormKimiaIdRoute
  _authenticatedFormKwluaIdRoute: typeof _authenticatedFormKwluaIdRoute
  _authenticatedFormMeterPlnIdRoute: typeof _authenticatedFormMeterPlnIdRoute
  _authenticatedFormMeterIdRoute: typeof _authenticatedFormMeterIdRoute
  _authenticatedFormPakaiKantorKodeRoute: typeof _authenticatedFormPakaiKantorKodeRoute
  _authenticatedFormPemakaianKantorIdRoute: typeof _authenticatedFormPemakaianKantorIdRoute
  _authenticatedFormPenggunaanBahanKimiaKodeRoute: typeof _authenticatedFormPenggunaanBahanKimiaKodeRoute
  _authenticatedFormPompAmpIdRoute: typeof _authenticatedFormPompAmpIdRoute
  _authenticatedFormPompAtmIdRoute: typeof _authenticatedFormPompAtmIdRoute
  _authenticatedFormRsvIdRoute: typeof _authenticatedFormRsvIdRoute
  _authenticatedFormSgaiIdRoute: typeof _authenticatedFormSgaiIdRoute
  _authenticatedFormWtpDebtIdRoute: typeof _authenticatedFormWtpDebtIdRoute
  _authenticatedPagesDetailCpltKodeRoute: typeof _authenticatedPagesDetailCpltKodeRoute
  _authenticatedPagesDetailCuciKodeRoute: typeof _authenticatedPagesDetailCuciKodeRoute
  _authenticatedPagesDetailDosisKodeRoute: typeof _authenticatedPagesDetailDosisKodeRoute
  _authenticatedPagesDetailGnstKodeRoute: typeof _authenticatedPagesDetailGnstKodeRoute
  _authenticatedPagesDetailKimiaKodeRoute: typeof _authenticatedPagesDetailKimiaKodeRoute
  _authenticatedPagesDetailKwlUaKodeRoute: typeof _authenticatedPagesDetailKwlUaKodeRoute
  _authenticatedPagesDetailMtrHrsKodeRoute: typeof _authenticatedPagesDetailMtrHrsKodeRoute
  _authenticatedPagesDetailPakaiKntrKodeRoute: typeof _authenticatedPagesDetailPakaiKntrKodeRoute
  _authenticatedPagesDetailPlnKodeRoute: typeof _authenticatedPagesDetailPlnKodeRoute
  _authenticatedPagesDetailPompAmpKodeRoute: typeof _authenticatedPagesDetailPompAmpKodeRoute
  _authenticatedPagesDetailPompAtmKodeRoute: typeof _authenticatedPagesDetailPompAtmKodeRoute
  _authenticatedPagesDetailRsvKodeRoute: typeof _authenticatedPagesDetailRsvKodeRoute
  _authenticatedPagesDetailSgaiKodeRoute: typeof _authenticatedPagesDetailSgaiKodeRoute
  _authenticatedPagesDetailWtpDebtKodeRoute: typeof _authenticatedPagesDetailWtpDebtKodeRoute
  _authenticatedPagesDetailKodeRoute: typeof _authenticatedPagesDetailKodeRoute
  _authenticatedFormCuciInputJenisRoute: typeof _authenticatedFormCuciInputJenisRoute
}

const _authenticatedRouteChildren: _authenticatedRouteChildren = {
  _authenticatedAnomaliRoute: _authenticatedAnomaliRoute,
  _authenticatedBahanKimiaRoute: _authenticatedBahanKimiaRoute,
  _authenticatedComingSoonRoute: _authenticatedComingSoonRoute,
  _authenticatedDashboardRoute: _authenticatedDashboardRoute,
  _authenticatedGantiPasswordRoute: _authenticatedGantiPasswordRoute,
  _authenticatedJadwalRoute: _authenticatedJadwalRoute,
  _authenticatedListDataRoute: _authenticatedListDataRoute,
  _authenticatedLogAktivitasRoute: _authenticatedLogAktivitasRoute,
  _authenticatedPencatatanHarianRoute: _authenticatedPencatatanHarianRoute,
  _authenticatedPenggunaanBahanKimiaRoute:
    _authenticatedPenggunaanBahanKimiaRoute,
  _authenticatedProfilRoute: _authenticatedProfilRoute,
  _authenticatedFormAnomaliRoute: _authenticatedFormAnomaliRoute,
  _authenticatedFormCipoletyIdRoute: _authenticatedFormCipoletyIdRoute,
  _authenticatedFormCuciIdRoute: _authenticatedFormCuciIdRoute,
  _authenticatedFormDosisIdRoute: _authenticatedFormDosisIdRoute,
  _authenticatedFormGensetKodeRoute: _authenticatedFormGensetKodeRoute,
  _authenticatedFormHoursPompaKodeRoute: _authenticatedFormHoursPompaKodeRoute,
  _authenticatedFormKimiaIdRoute: _authenticatedFormKimiaIdRoute,
  _authenticatedFormKwluaIdRoute: _authenticatedFormKwluaIdRoute,
  _authenticatedFormMeterPlnIdRoute: _authenticatedFormMeterPlnIdRoute,
  _authenticatedFormMeterIdRoute: _authenticatedFormMeterIdRoute,
  _authenticatedFormPakaiKantorKodeRoute:
    _authenticatedFormPakaiKantorKodeRoute,
  _authenticatedFormPemakaianKantorIdRoute:
    _authenticatedFormPemakaianKantorIdRoute,
  _authenticatedFormPenggunaanBahanKimiaKodeRoute:
    _authenticatedFormPenggunaanBahanKimiaKodeRoute,
  _authenticatedFormPompAmpIdRoute: _authenticatedFormPompAmpIdRoute,
  _authenticatedFormPompAtmIdRoute: _authenticatedFormPompAtmIdRoute,
  _authenticatedFormRsvIdRoute: _authenticatedFormRsvIdRoute,
  _authenticatedFormSgaiIdRoute: _authenticatedFormSgaiIdRoute,
  _authenticatedFormWtpDebtIdRoute: _authenticatedFormWtpDebtIdRoute,
  _authenticatedPagesDetailCpltKodeRoute:
    _authenticatedPagesDetailCpltKodeRoute,
  _authenticatedPagesDetailCuciKodeRoute:
    _authenticatedPagesDetailCuciKodeRoute,
  _authenticatedPagesDetailDosisKodeRoute:
    _authenticatedPagesDetailDosisKodeRoute,
  _authenticatedPagesDetailGnstKodeRoute:
    _authenticatedPagesDetailGnstKodeRoute,
  _authenticatedPagesDetailKimiaKodeRoute:
    _authenticatedPagesDetailKimiaKodeRoute,
  _authenticatedPagesDetailKwlUaKodeRoute:
    _authenticatedPagesDetailKwlUaKodeRoute,
  _authenticatedPagesDetailMtrHrsKodeRoute:
    _authenticatedPagesDetailMtrHrsKodeRoute,
  _authenticatedPagesDetailPakaiKntrKodeRoute:
    _authenticatedPagesDetailPakaiKntrKodeRoute,
  _authenticatedPagesDetailPlnKodeRoute: _authenticatedPagesDetailPlnKodeRoute,
  _authenticatedPagesDetailPompAmpKodeRoute:
    _authenticatedPagesDetailPompAmpKodeRoute,
  _authenticatedPagesDetailPompAtmKodeRoute:
    _authenticatedPagesDetailPompAtmKodeRoute,
  _authenticatedPagesDetailRsvKodeRoute: _authenticatedPagesDetailRsvKodeRoute,
  _authenticatedPagesDetailSgaiKodeRoute:
    _authenticatedPagesDetailSgaiKodeRoute,
  _authenticatedPagesDetailWtpDebtKodeRoute:
    _authenticatedPagesDetailWtpDebtKodeRoute,
  _authenticatedPagesDetailKodeRoute: _authenticatedPagesDetailKodeRoute,
  _authenticatedFormCuciInputJenisRoute: _authenticatedFormCuciInputJenisRoute,
}

const _authenticatedRouteWithChildren = _authenticatedRoute._addFileChildren(
  _authenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _authenticatedRoute: _authenticatedRouteWithChildren,
  KameraRoute: KameraRoute,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
